// demo/zhihu-react/src/Containers/Login/Background/index.js
import React from 'react';
import styles from './index.less';
import Particle from 'zhihu-particle';

export default class Background extends React.Component {
    componentDidMount() {
        new Particle(this.background, {interactive: true});
    }

    render() {
        return (
            <div ref={(background) => {
                this.background = background;
            }}
                 className={styles.background}
            />
        )
    }
}

// demo/zhihu-vue/src/components/Login/Background/index.vue
<template>
    <div class="background"></div>
</template>
<style scoped>
    .background {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 0;
        overflow: hidden;
    }
</style>
<script>
    import Particle from 'zhihu-particle'
    export default {
        name: 'layout',
        mounted(){
            new Particle(this.$el, {interactive: true})
        }
    }
</script>
